training:
  synth_only: true
  batch_size: 12
  batch_size_val: 24
  const_max: 2
  n_epochs_warmup: 50
  num_workers: 6
  n_epochs: 200
  early_stop_patience: 200
  accumulate_batches: 1
  gradient_clip: 0.0
  median_window: 7
  val_thresholds: [0.5]
  n_test_thresholds: 50
  ema_factor: 0.999
  self_sup_loss: mse
  backend: dp
  validation_interval: 1
  weak_split: 0.9
  seed: 42
  precision: 32
  mixup: soft
  obj_metric_synth_type: intersection
scaler:
  statistic: instance
  normtype: minmax
  dims: [1, 2]
  savepath: ./scaler.ckpt
data:
  synth_folder: "./runtime_data/dcase_synth/audio/train/synthetic21_train/soundscapes_16k"
  synth_folder_44k: "/mnt/d/Downloads/Compressed/dcase_synth/audio/train/synthetic21_train/soundscapes"
  synth_tsv: "/mnt/d/Downloads/Compressed/dcase_synth/metadata/train/synthetic21_train/soundscapes.tsv"
  strong_folder: ""
  strong_folder_44k: ""
  strong_tsv: ""
  weak_folder: ""
  weak_folder_44k: ""
  weak_tsv: ""
  unlabeled_folder: ""
  unlabeled_folder_44k: ""
  synth_val_folder: "./runtime_data/dcase_synth/audio/validation/synthetic21_validation/soundscapes_16k"
  synth_val_folder_44k: "/mnt/d/Downloads/Compressed/dcase_synth/audio/validation/synthetic21_validation/soundscapes"
  synth_val_tsv: "/mnt/d/Downloads/Compressed/dcase_synth/metadata/validation/synthetic21_validation/soundscapes.tsv"
  synth_val_dur: "./runtime_data/dcase_synth/metadata/validation/synthetic21_validation/durations.tsv"
  test_folder: "./runtime_data/dcase_synth/audio/validation/synthetic21_validation/soundscapes_16k"
  test_folder_44k: "/mnt/d/Downloads/Compressed/dcase_synth/audio/validation/synthetic21_validation/soundscapes"
  test_tsv: "/mnt/d/Downloads/Compressed/dcase_synth/metadata/validation/synthetic21_validation/soundscapes.tsv"
  test_dur: "./runtime_data/dcase_synth/metadata/validation/synthetic21_validation/durations.tsv"
  eval_folder: ""
  eval_folder_44k: ""
  audio_max_len: 10
  fs: 16000
  net_subsample: 4
opt:
  lr: 0.001
feats:
  n_mels: 128
  n_filters: 2048
  hop_length: 256
  n_window: 2048
  sample_rate: 16000
  f_min: 0
  f_max: 8000
net:
  dropout: 0.5
  rnn_layers: 2
  n_in_channel: 1
  nclass: 10
  attention: true
  n_RNN_cell: 128
  activation: glu
  rnn_type: BGRU
  kernel_size: [3, 3, 3, 3, 3, 3, 3]
  padding: [1, 1, 1, 1, 1, 1, 1]
  stride: [1, 1, 1, 1, 1, 1, 1]
  nb_filters: [16, 32, 64, 128, 128, 128, 128]
  pooling: [[2, 2], [2, 2], [1, 2], [1, 2], [1, 2], [1, 2], [1, 2]]
  dropout_recurrent: 0
